services:
  yukchi-front-dev:
    container_name: yukchi-front-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
    restart: unless-stopped
    ports:
      - "${HOST:-0.0.0.0}:${PORT}:80"
    environment:
      - TZ=Asia/Tashkent
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 30s
      timeout: 5s
      retries: 3
