export const countries = [
  { label: 'O‘zbekiston', value: 'uzbekistan' },
  { label: 'Rossiya', value: 'russia' },
  { label: 'Belarusiya', value: 'belarus' },
  { label: 'Qozog‘iston', value: 'kazakhstan' },
  { label: 'Xitoy', value: 'china' },
  { label: 'Turkiya', value: 'turkey' },
  { label: 'Qirg‘iziston', value: 'kyrgyzstan' },
  { label: 'Tajikiston', value: 'tajikistan' },
  { label: 'Turkmaniston', value: 'turkmenistan' },
  { label: 'Pokiston', value: 'pakistan' },
  { label: 'Eron', value: 'iran' },
  { label: 'Afg‘oniston', value: 'afghanistan' },
  { label: 'Gruziya', value: 'georgia' },
] as const
