export const routeData = [
  {
    indexedName: "uzbekistan",
    countryNameCyr: "узбекистон",
    countryNameLat: "O'zbekiston",
    alias: [],
    alias_cyr: [],
    regions: [
      {
        id: 1,
        name: "Toshkent shahri",
        indexedName: "tashkent_city",
        center: "Toshkent",
        coords: { lat: 41.2995, lng: 69.2401 },
        alias: [
          "toshkent",
          "tashkent",
          "toshent",
          "toshken",
          "poytaxt",
          "tashkent city",
          "toshkent shahar",
          "tosh",
          "toshkent sh",
          "tashkent",
          "chilonzor",
          "mirobod",
          "mirzo ulug'bek",
          "olmazor",
          "sergeli",
          "shayxontohur",
          "uchtepa",
          "yakkasaroy",
          "yangihayot",
          "yashnobod",
          "yunusobod",
          "yangi toshkent",
          "taşkent",
          "towkent",
        ],
        alias_cyr: [
          "тошкент",
          "ташкент",
          "тошент",
          "тошкен",
          "пойтахт",
          "тошкент шаҳар",
          "тош",
          "тошкент ш",
          "ташкент",
          "аркбулок",
          "уртасарой",
          "чукурсай",
          "яшнабод",
        ],
      },
      {
        id: 2,
        name: "Toshkent viloyati",
        indexedName: "tashkent_region",
        center: "Nurafshon",
        coords: { lat: 41.0057729, lng: 71.6436028 },
        alias: [
          "toshkent viloyati",
          "toshkent obl",
          "tashkent obl",
          "tashkent region",
          "nurafshon",
          "chirchiq",
          "yangiyo'l",
          "bekobod",
          "olmaliq",
          "olmalik",
          "angren",
          "ahangaran",
          "ohangaron",
          "toytepa",
        ],
        alias_cyr: [
          "тошкент вилояти",
          "тошкент обл",
          "ташкентская область",
          "ташкент обл",
          "нурафшон",
          "чирчиқ",
          "янгийўл",
          "бекобод",
          "ахангаран",
          "охангарон",
          "ангрен",
          "олмалик",
          "назарбек",
        ],
      },
      {
        id: 3,
        name: "Andijon viloyati",
        indexedName: "andijan",
        center: "Andijon",
        coords: { lat: 40.8153561, lng: 72.28375 },
        alias: [
          "andijon",
          "andijan",
          "andizhan",
          "andijanlik",
          "asaka",
          "shaxrixon",
          "and",
          "baliqchi",
          "jalaquduq",
          "qorasuv",
          "qorgontepa",
          "marhamat",
          "paxtobod",
          "shahrihon",
          "ulug'nor",
          "xonabod",
        ],
        alias_cyr: [
          "андижон",
          "андижан",
          "андижонлик",
          "асака",
          "шахрихон",
          "анд",
          "хожабод",
        ],
      },
      {
        id: 4,
        name: "Farg'ona viloyati",
        indexedName: "ferghana",
        center: "Farg'ona",
        coords: { lat: 40.3855561, lng: 71.78375 },
        alias: [
          "fargona",
          "ferghana",
          "farg'ona",
          "fergana",
          "vodiy",
          "vadiy",
          "qo'qon",
          "margilon",
          "rishton",
          "oltiariq",
          "buvayda",
          "vadil",
          "vodil",
          "qoʻqon",
          "qoqon",
          "kokand",
          "quva",
          "quvasoy",
          "toshloq",
          "uchkoprik",
          "xonabod",
          "yaypan",
          "qoshtepa",
          "oltinariq",
        ],
        alias_cyr: [
          "фарғона",
          "фергана",
          "фаргона",
          "қўқон",
          "қуқон",
          "марғилон",
          "марғулон",
          "риштон",
          "олтиариқ",
          "бувайda",
          "вадил",
          "водил",
          "кукон",
          "коканд",
          "маргилон",
        ],
      },
      {
        id: 5,
        name: "Namangan viloyati",
        indexedName: "namangan",
        center: "Namangan",
        coords: { lat: 40.9555061, lng: 71.1097749 },
        alias: [
          "namangan",
          "namanganlik",
          "namangan viloyati",
          "chust",
          "kosonsoy",
          "pop",
          "uchqo'rg'on",
          "nam",
          "norin",
          "toraqorgon",
        ],
        alias_cyr: [
          "наманган",
          "наманган вилояти",
          "чуст",
          "косонсой",
          "поп",
          "нам",
          "мингбулок",
          "учкорган",
        ],
      },
      {
        id: 6,
        name: "Sirdaryo viloyati",
        indexedName: "syrdarya",
        center: "Guliston",
        coords: { lat: 40.4837431, lng: 68.7878923 },
        alias: [
          "sirdaryo",
          "sirdaryo viloyati",
          "guliston",
          "yangiyer",
          "syrdarya",
          "sirdarya",
          "mirzaobod",
          "sardoba",
          "sayxunobod",
          "shirin",
          "yangiyer",
        ],
        alias_cyr: [
          "сирдарё",
          "сырдарья",
          "сирдарё вилояти",
          "гулистон",
          "янгиер",
          "сирдаре",
        ],
      },
      {
        id: 7,
        name: "Jizzax viloyati",
        indexedName: "jizzakh",
        center: "Jizzax",
        coords: { lat: 40.1255561, lng: 67.84375 },
        alias: [
          "jizzax",
          "jizzakh",
          "djizak",
          "jizax",
          "zomin",
          "forish",
          "baxmal",
          "dashtobod",
          "gagarin",
          "g'allaorol",
          "mirzacho'l",
          "paxtakor",
          "sharof rashidov",
          "zafarobod",
        ],
        alias_cyr: ["жиззах", "джизак", "жизах", "зомин", "фориш"],
      },
      {
        id: 8,
        name: "Samarqand viloyati",
        indexedName: "samarkand",
        center: "Samarqand",
        alias: [
          "samarqand",
          "samarkand",
          "samarkandskaya oblast",
          "sam",
          "kattaqo'rg'on",
          "urgut",
          "samarkant",
          "semerkand",
          "bulg'ur",
          "ishtixon",
          "jomboy",
          "juma",
          "narpay",
          "nurobod",
          "oqdaryo",
          "pastdargom",
          "payariq",
          "qoshrabot",
          "toyloq",
        ],
        alias_cyr: [
          "самарқанд",
          "самарканд",
          "самаркандская область",
          "сам",
          "каттақўрғон",
          "ургут",
          "курган",
        ],
      },
      {
        id: 9,
        name: "Buxoro viloyati",
        indexedName: "bukhara",
        center: "Buxoro",
        coords: { lat: 40.1255561, lng: 67.84375 },
        alias: [
          "buxoro",
          "bukhara",
          "buxara",
          "vuxoro",
          "g'ijduvon",
          "vobkent",
          "qorako'l",
          "jondor",
          "kogon",
          "olot",
          "qorakol",
          "qorovulbozor",
          "romitan",
        ],
        alias_cyr: [
          "бухоро",
          "бухара",
          "вухоро",
          "ғиждувон",
          "вобкент",
          "қоракўл",
          "каракуль",
        ],
      },
      {
        id: 10,
        name: "Navoiy viloyati",
        indexedName: "navoi",
        center: "Navoiy",
        alias: [
          "navoiy",
          "navoi",
          "navoiyskaya oblast",
          "uchquduq",
          "zarafshon",
          "karmana",
          "konimex",
          "nurota",
          "qiziltepa",
          "tomdi",
        ],
        alias_cyr: [
          "навоий",
          "навои",
          "навоийская область",
          "навоийская обл",
          "учқудуқ",
          "зарафшон",
          "новойи",
          "кизил тепа",
        ],
      },
      {
        id: 11,
        name: "Qashqadaryo viloyati",
        indexedName: "kashkadarya",
        center: "Qarshi",
        alias: [
          "qashqadaryo",
          "kashkadarya",
          "kashkadaryinskaya",
          "qarshi",
          "karshi",
          "nasaf",
          "shaxrisabz",
          "qash",
          "shahrisabz",
          "yakkabog",
          "yangi nishon",
          "yettitom",
          "chiroqchi",
          "guzor",
          "kasbi",
          "kitob",
          "koson",
          "muborak",
          "qamashi",
          "nishon",
        ],
        alias_cyr: [
          "қашқадарё",
          "кашкадарья",
          "кашкадарьинская область",
          "қарши",
          "карши",
          "насаф",
          "қаш",
          "карши",
        ],
      },
      {
        id: 12,
        name: "Surxondaryo viloyati",
        indexedName: "surkhandarya",
        center: "Termiz",
        alias: [
          "surxondaryo",
          "surxandaryo",
          "surkhondarya",
          "surxandarya",
          "termiz",
          "termez",
          "denov",
          "surxon",
          "angor",
          "boysun",
          "jarqorgon",
          "muzrabot",
          "qumqorgon",
          "sherobod",
          "sho'rchi",
          "uchqizil",
        ],
        alias_cyr: [
          "сурхондарё",
          "сурхандарё",
          "сурхандарья",
          "термиз",
          "термез",
          "денов",
          "сурхон",
          "айратон",
          "ипок",
        ],
      },
      {
        id: 13,
        name: "Xorazm viloyati",
        indexedName: "khorezm",
        center: "Urganch",
        alias: [
          "xorazm",
          "khorezm",
          "kharezm",
          "urganch",
          "urgench",
          "xiva",
          "khiva",
          "shovot",
          "xonqa",
          "yangiariq",
          "xorazim",
        ],
        alias_cyr: [
          "хоразм",
          "хорезм",
          "харезм",
          "урганч",
          "ургенч",
          "хива",
          "хоразим",
        ],
      },
      {
        id: 14,
        name: "Qoraqalpog'iston Respublikasi",
        indexedName: "karakalpakstan",
        center: "Nukus",
        alias: [
          "qoraqalpog'iston",
          "qoraqalpogiston",
          "karakalpakstan",
          "karakalpakiya",
          "nukus",
          "nokus",
          "qrq",
          "bo'ston",
          "chimboy",
          "mang'it",
          "mo'ynoq",
        ],
        alias_cyr: [
          "қорақалпоғистон",
          "каракалпакстан",
          "каракалпакия",
          "нукус",
          "нокус",
          "қрқ",
          "тўрткўл",
          "турткул",
        ],
      },
    ],
  },
  {
    indexedName: "russia",
    countryNameCyr: "Россия",
    countryNameLat: "Rossiya",
    alias: ["russia", "rossiya", "ru", "rus"],
    alias_cyr: ["россия", "рф", "ру", "рус"],
    regions: [
      {
        id: 1,
        name: "Moskva",
        indexedName: "moscow",
        center: "Moskva",
        alias: [
          "moskva",
          "moscow",
          "moskovskaya oblast",
          "mo",
          "msk",
          "maskva",
        ],
        alias_cyr: ["москва", "московская область", "мо", "мск", "масква"],
      },
      {
        id: 2,
        name: "Sankt-Peterburg",
        indexedName: "saint_petersburg",
        center: "Sankt-Peterburg",
        alias: [
          "saint petersburg",
          "st petersburg",
          "piter",
          "spb",
          "sankt-peterburg",
        ],
        alias_cyr: [
          "санкт-петербург",
          "питер",
          "спб",
          "санкт петербург",
          "ленинград",
        ],
      },
      {
        id: 3,
        name: "Novosibirsk",
        indexedName: "novosibirsk",
        center: "Novosibirsk",
        alias: ["novosibirsk", "nvs", "sibir", "nsk"],
        alias_cyr: ["новосибирск", "нвс", "сибирь", "нск"],
      },
      {
        id: 4,
        name: "Yekaterinburg",
        indexedName: "yekaterinburg",
        center: "Yekaterinburg",
        alias: ["yekaterinburg", "ekb", "ekaterinburg", "sverdlovsk", "burg"],
        alias_cyr: ["екатеринбург", "екб", "свердловск", "бург"],
      },
      {
        id: 5,
        name: "Kazan",
        indexedName: "kazan",
        center: "Kazan",
        alias: ["kazan", "qazan", "tatarstan", "qozon"],
        alias_cyr: ["казань", "татарстан", "қазон"],
      },
      {
        id: 6,
        name: "Chelyabinsk",
        indexedName: "chelyabinsk",
        center: "Chelyabinsk",
        alias: ["chelyabinsk", "chelyaba", "chelabinsk", "chel"],
        alias_cyr: ["челябинск", "челяба", "челабинск", "чел"],
      },
      {
        id: 7,
        name: "Samara",
        indexedName: "samara",
        center: "Samara",
        alias: ["samara", "kuybishev"],
        alias_cyr: ["самара", "куйбышев"],
      },
      {
        id: 8,
        name: "Rostov-na-Donu",
        indexedName: "rostov_on_don",
        center: "Rostov-na-Donu",
        alias: ["rostov", "rostov-on-don", "rostov na donu", "rnd"],
        alias_cyr: ["ростов", "ростов-на-дону", "ростов на дону", "рнд"],
      },
      {
        id: 9,
        name: "Ufa",
        indexedName: "ufa",
        center: "Ufa",
        alias: ["ufa", "bashkortostan", "bashkiria"],
        alias_cyr: ["уфа", "башкортостан", "башкирия"],
      },
      {
        id: 10,
        name: "Volgograd",
        indexedName: "volgograd",
        center: "Volgograd",
        alias: ["volgograd", "stalingrad"],
        alias_cyr: ["волгоград", "сталинград"],
      },
      {
        id: 11,
        name: "Krasnodar",
        indexedName: "krasnodar",
        center: "Krasnodar",
        alias: ["krasnodar", "kuban", "krd"],
        alias_cyr: ["краснодар", "кубань", "крд"],
      },
      {
        id: 12,
        name: "Omsk",
        indexedName: "omsk",
        center: "Omsk",
        alias: ["omsk"],
        alias_cyr: ["омск"],
      },
      {
        id: 13,
        name: "Voronej",
        indexedName: "voronezh",
        center: "Voronezh",
        alias: ["voronezh", "voronej"],
        alias_cyr: ["воронеж"],
      },
      {
        id: 14,
        name: "Kirov",
        indexedName: "kirov",
        center: "Kirov",
        alias: ["kirov", "vyatka", "kirovskaya oblast"],
        alias_cyr: ["киров", "вятка", "кировская область"],
      },
      {
        id: 15,
        name: "Nizhny Novgorod",
        indexedName: "nizhny_novgorod",
        center: "Nizhny Novgorod",
        alias: [
          "nizhny novgorod",
          "nnov",
          "nn",
          "gorky",
          "nizhegorodskaya",
          "arzamas",
          "baraba",
        ],
        alias_cyr: [
          "нижний новгород",
          "нн",
          "нижний",
          "горький",
          "нижегородская",
          "арзамас",
          "бараба",
        ],
      },
      {
        id: 16,
        name: "Tomsk",
        indexedName: "tomsk",
        center: "Tomsk",
        alias: ["tomsk", "tomskaya oblast", "tomsk oblast", "asino"],
        alias_cyr: ["томск", "томская область", "томск область", "асино"],
      },
      {
        id: 17,
        name: "Kemerovo",
        indexedName: "kemerovo",
        center: "Kemerovo",
        alias: ["kemerovo", "kem", "kuzbass", "shcheglovsk", "novokuznetsk"],
        alias_cyr: ["кемерово", "кем", "кузбасс", "щегловск", "новокузнецк"],
      },
      {
        id: 18,
        name: "Altai Krai",
        indexedName: "altay_krai",
        center: "Barnaul",
        alias: ["altay krai", "altay", "barnaul", "rubtsovsk", "biysk"],
        alias_cyr: ["алтайский край", "алтай", "барнаул", "рубцовск", "бийск"],
      },
      {
        id: 19,
        name: "Arkhangelsk Oblast",
        indexedName: "arkhangelsk_oblast",
        center: "Arkhangelsk",
        alias: ["arkhangelsk", "arkhangelskaya oblast", "arkhangelsk oblast"],
        alias_cyr: [
          "архангельск",
          "архангельская область",
          "архангельск область",
        ],
      },
      {
        id: 20,
        name: "Saratov",
        indexedName: "saratov",
        center: "Saratov",
        alias: ["saratov", "saratovskaya oblast", "saratov oblast"],
        alias_cyr: ["саратов", "саратовская область", "саратов область"],
      },
      {
        id: 21,
        name: "Ulyanovsk",
        indexedName: "ulyanovsk",
        center: "Ulyanovsk",
        alias: ["ulyanovsk", "ulyanovskaya oblast", "ulyanovsk oblast"],
        alias_cyr: ["ульяновск", "ульяновская область", "ульяновск область"],
      },
      {
        id: 22,
        name: "Amur Oblast",
        indexedName: "amur_oblast",
        center: "Blagoveshchensk",
        alias: ["amur oblast", "amurskaya oblast", "blagoveshchensk", "blg"],
        alias_cyr: ["амурская область", "амурская", "благовещенск", "блг"],
      },
      {
        id: 23,
        name: "Astrakhan Oblast",
        indexedName: "astrakhan_oblast",
        center: "Astrakhan",
        alias: [
          "astrakhan oblast",
          "astrakhanskaya oblast",
          "astrakhan",
          "ast",
        ],
        alias_cyr: ["астраханская область", "астрахань", "астраханская", "аст"],
      },
      {
        id: 24,
        name: "Belgorod Oblast",
        indexedName: "belgorod_oblast",
        center: "Belgorod",
        alias: ["belgorod oblast", "belgorodskaya oblast", "belgorod", "bel"],
        alias_cyr: ["белгородская область", "белгород", "белгородская", "бел"],
      },
      {
        id: 25,
        name: "Bryansk Oblast",
        indexedName: "bryansk_oblast",
        center: "Bryansk",
        alias: ["bryansk oblast", "bryanskaya oblast", "bryansk", "brn"],
        alias_cyr: ["брянская область", "брянск", "брянская", "брн"],
      },
      {
        id: 26,
        name: "Vladimir Oblast",
        indexedName: "vladimir_oblast",
        center: "Vladimir",
        alias: ["vladimir oblast", "vladimirskaya oblast", "vladimir", "vlm"],
        alias_cyr: ["владимирская область", "владимир", "владимирская", "влм"],
      },
      {
        id: 27,
        name: "Vologda Oblast",
        indexedName: "vologda_oblast",
        center: "Vologda",
        alias: ["vologda oblast", "vologodskaya oblast", "vologda", "vol"],
        alias_cyr: ["вологодская область", "вологда", "вологодская", "вол"],
      },
      {
        id: 28,
        name: "Ivanovo Oblast",
        indexedName: "ivanovo_oblast",
        center: "Ivanovo",
        alias: ["ivanovo oblast", "ivanovskaya oblast", "ivanovo", "iva"],
        alias_cyr: ["ивановская область", "иваново", "ивановская", "ива"],
      },
      {
        id: 29,
        name: "Irkutsk Oblast",
        indexedName: "irkutsk_oblast",
        center: "Irkutsk",
        alias: ["irkutsk oblast", "irkutskaya oblast", "irkutsk", "irk"],
        alias_cyr: ["иркутская область", "иркутск", "иркутская", "ирк"],
      },
      {
        id: 30,
        name: "Kaliningrad Oblast",
        indexedName: "kaliningrad_oblast",
        center: "Kaliningrad",
        alias: [
          "kaliningrad oblast",
          "kaliningradskaya oblast",
          "kaliningrad",
          "klg",
        ],
        alias_cyr: [
          "калининградская область",
          "калининград",
          "калининградская",
          "клг",
        ],
      },
      {
        id: 31,
        name: "Kaluga Oblast",
        indexedName: "kaluga_oblast",
        center: "Kaluga",
        alias: ["kaluga oblast", "kaluzhskaya oblast", "kaluga", "klzh"],
        alias_cyr: ["калужская область", "калуга", "калужская", "клж"],
      },
      {
        id: 32,
        name: "Kostroma Oblast",
        indexedName: "kostroma_oblast",
        center: "Kostroma",
        alias: ["kostroma oblast", "kostromskaya oblast", "kostroma", "kos"],
        alias_cyr: ["костромская область", "кострома", "костромская", "кос"],
      },
      {
        id: 33,
        name: "Kurgan Oblast",
        indexedName: "kurgan_oblast",
        center: "Kurgan",
        alias: ["kurgan oblast", "kurganskaya oblast", "kurgan", "kug"],
        alias_cyr: ["курганская область", "курган", "курганская", "куг"],
      },
      {
        id: 34,
        name: "Kursk Oblast",
        indexedName: "kursk_oblast",
        center: "Kursk",
        alias: ["kursk oblast", "kurskaya oblast", "kursk", "krs"],
        alias_cyr: ["курская область", "курск", "курская", "крс"],
      },
      {
        id: 35,
        name: "Lipetsk Oblast",
        indexedName: "lipetsk_oblast",
        center: "Lipetsk",
        alias: ["lipetsk oblast", "lipetskaya oblast", "lipetsk", "lpt"],
        alias_cyr: ["липецкая область", "липецк", "липецкая", "лпц"],
      },
      {
        id: 36,
        name: "Magadan Oblast",
        indexedName: "magadan_oblast",
        center: "Magadan",
        alias: ["magadan oblast", "magadanskaya oblast", "magadan", "mag"],
        alias_cyr: ["магаданская область", "магадан", "магаданская", "маг"],
      },
      {
        id: 37,
        name: "Murmansk Oblast",
        indexedName: "murmansk_oblast",
        center: "Murmansk",
        alias: ["murmansk oblast", "murmanskaya oblast", "murmansk", "mur"],
        alias_cyr: ["мурманская область", "мурманск", "мурманская", "мур"],
      },
      {
        id: 38,
        name: "Novgorod Oblast",
        indexedName: "novgorod_oblast",
        center: "Veliky Novgorod",
        alias: ["novgorod oblast", "novgorodskaya oblast", "novgorod", "nvg"],
        alias_cyr: ["новгородская область", "новгород", "новгородская", "нвг"],
      },
      {
        id: 39,
        name: "Orenburg Oblast",
        indexedName: "orenburg_oblast",
        center: "Orenburg",
        alias: ["orenburg oblast", "orenburgskaya oblast", "orenburg", "orb"],
        alias_cyr: ["оренбургская область", "оренбург", "оренбургская", "орб"],
      },
      {
        id: 40,
        name: "Oryol Oblast",
        indexedName: "oryol_oblast",
        center: "Oryol",
        alias: ["oryol oblast", "orlovskaya oblast", "oryol", "orel", "orl"],
        alias_cyr: ["орловская область", "орел", "орёл", "орловская", "орл"],
      },
      {
        id: 41,
        name: "Penza Oblast",
        indexedName: "penza_oblast",
        center: "Penza",
        alias: ["penza oblast", "penzenskaya oblast", "penza", "pnz"],
        alias_cyr: ["пензенская область", "пенза", "пензенская", "пнз"],
      },
      {
        id: 42,
        name: "Pskov Oblast",
        indexedName: "pskov_oblast",
        center: "Pskov",
        alias: ["pskov oblast", "pskovskaya oblast", "pskov", "psk"],
        alias_cyr: ["псковская область", "псков", "псковская", "пск"],
      },
      {
        id: 43,
        name: "Ryazan Oblast",
        indexedName: "ryazan_oblast",
        center: "Ryazan",
        alias: ["ryazan oblast", "ryazanskaya oblast", "ryazan", "ryaz"],
        alias_cyr: ["рязанская область", "рязань", "рязанская", "ряз"],
      },
      {
        id: 44,
        name: "Sakhalin Oblast",
        indexedName: "sakhalin_oblast",
        center: "Yuzhno-Sakhalinsk",
        alias: [
          "sakhalin oblast",
          "sakhalinskaya oblast",
          "yuzhno-sakhalinsk",
          "yuskh",
        ],
        alias_cyr: [
          "сахалинская область",
          "южно-сахалинск",
          "сахалинская",
          "юсх",
        ],
      },
      {
        id: 45,
        name: "Smolensk Oblast",
        indexedName: "smolensk_oblast",
        center: "Smolensk",
        alias: ["smolensk oblast", "smolenskaya oblast", "smolensk", "smo"],
        alias_cyr: ["смоленская область", "смоленск", "смоленская", "смо"],
      },
      {
        id: 46,
        name: "Tambov Oblast",
        indexedName: "tambov_oblast",
        center: "Tambov",
        alias: ["tambov oblast", "tambovskaya oblast", "tambov", "tmb"],
        alias_cyr: ["тамбовская область", "тамбов", "тамбовская", "тмб"],
      },
      {
        id: 47,
        name: "Tver Oblast",
        indexedName: "tver_oblast",
        center: "Tver",
        alias: ["tver oblast", "tverskaya oblast", "tver", "tve"],
        alias_cyr: ["тверская область", "тверь", "тверская", "тве"],
      },
      {
        id: 48,
        name: "Tula Oblast",
        indexedName: "tula_oblast",
        center: "Tula",
        alias: ["tula oblast", "tulskaya oblast", "tula", "tul"],
        alias_cyr: ["тульская область", "тула", "тульская", "тул"],
      },
      {
        id: 49,
        name: "Tyumen Oblast",
        indexedName: "tyumen_oblast",
        center: "Tyumen",
        alias: [
          "tyumen oblast",
          "tyumenskaya oblast",
          "tyumen",
          "tyum",
          "tobolsk",
        ],
        alias_cyr: [
          "тюменская область",
          "тюмень",
          "тюменская",
          "тюм",
          "тобольск",
        ],
      },
      {
        id: 50,
        name: "Yaroslavl Oblast",
        indexedName: "yaroslavl_oblast",
        center: "Yaroslavl",
        alias: [
          "yaroslavl oblast",
          "yaroslavskaya oblast",
          "yaroslavl",
          "yarl",
        ],
        alias_cyr: ["ярославская область", "ярославль", "ярославская", "ярл"],
      },
      {
        id: 51,
        name: "Jewish Autonomous Oblast",
        indexedName: "jewish_autonomous_oblast",
        center: "Birobidzhan",
        alias: ["jewish oblast", "evreyskaya oblast", "birobidzhan", "bir"],
        alias_cyr: [
          "еврейская автономная область",
          "еврейская",
          "биробиджан",
          "бир",
        ],
      },
    ],
  },
  {
    indexedName: "kazakhstan",
    countryNameCyr: "Қозоғистон",
    countryNameLat: "Qozog'iston",
    alias: ["kazakhstan", "kazaxstan", "kz", "kaz"],
    alias_cyr: ["қозоғистон", "казахстан", "кз", "каз"],
    regions: [
      {
        id: 1,
        name: "Olmaota",
        indexedName: "almaty",
        center: "Almaty",
        alias: ["almaty", "almati", "alma-ata", "almaata", "almatinskiy"],
        alias_cyr: ["олмаота", "алматы", "алмата", "алматинский"],
      },
      {
        id: 2,
        name: "Ostona",
        indexedName: "astana",
        center: "Astana",
        alias: ["astana", "nur-sultan", "nursultan", "akmola"],
        alias_cyr: ["астана", "нурсултан", "нур-султан", "акмола"],
      },
      {
        id: 3,
        name: "Chimkent",
        indexedName: "shymkent",
        center: "Shymkent",
        alias: ["shymkent", "chimkent", "turkestan region"],
        alias_cyr: ["чимкент", "шымкент", "туркестан"],
      },
      {
        id: 4,
        name: "Aktau",
        indexedName: "aktau",
        center: "Aktau",
        alias: ["aktau", "mangistau", "shevchenko"],
        alias_cyr: ["актау", "мангистау", "шевченко"],
      },
      {
        id: 5,
        name: "Atirau",
        indexedName: "atyrau",
        center: "Atyrau",
        alias: ["atyrau", "atirau", "guryev"],
        alias_cyr: ["атырау", "атирау", "гурьев"],
      },
      {
        id: 6,
        name: "Aqto'be",
        indexedName: "aktobe",
        center: "Aktobe",
        alias: ["aktobe", "aktobe", "aktyubinsk"],
        alias_cyr: ["ақтўбе", "актобе", "актюбинск"],
      },
      {
        id: 7,
        name: "Qarag'anda",
        indexedName: "karaganda",
        center: "Karaganda",
        alias: ["karaganda", "qaraganda"],
        alias_cyr: ["қарағанда", "караганда"],
      },
      {
        id: 8,
        name: "Taraz",
        indexedName: "taraz",
        center: "Taraz",
        alias: ["taraz", "jambul", "zhambyl"],
        alias_cyr: ["тараз", "жамбул", "жамбыл"],
      },
      {
        id: 9,
        name: "Qizilo'rda",
        indexedName: "kyzylorda",
        center: "Kyzylorda",
        alias: ["kyzylorda", "qizilorda", "kizilorda"],
        alias_cyr: ["қизилорда", "кызылорда", "кизилорда"],
      },
      {
        id: 10,
        name: "Pavlodar",
        indexedName: "pavlodar",
        center: "Pavlodar",
        alias: ["pavlodar"],
        alias_cyr: ["павлодар"],
      },
    ],
  },
  {
    indexedName: "kyrgyzstan",
    countryNameCyr: "Қирғизистон",
    countryNameLat: "Qirg'iziston",
    alias: ["kyrgyzstan", "kirgiziya", "kg"],
    alias_cyr: ["қирғизистон", "киргизия", "қж"],
    regions: [
      {
        id: 1,
        name: "Bishkek shahri",
        indexedName: "bishkek",
        center: "Bishkek",
        alias: ["bishkek", "frunze", "kg_capital"],
        alias_cyr: ["бишкек", "фрунзе", "бшк"],
      },
      {
        id: 2,
        name: "O'sh shahri",
        indexedName: "osh_city",
        center: "O'sh",
        alias: ["osh shahar", "osh city"],
        alias_cyr: ["ўш", "ош", "ош шаҳри"],
      },
      {
        id: 3,
        name: "Chuy viloyati",
        indexedName: "chuy",
        center: "Bishkek",
        alias: ["chuy", "chuy viloyati", "tokmok", "kant"],
        alias_cyr: ["чуй", "чуй вилояти", "тўқмоқ", "токмок", "кант"],
      },
      {
        id: 4,
        name: "O'sh viloyati",
        indexedName: "osh_region",
        center: "O'sh",
        alias: ["osh", "osh region", "uzgen", "qorasuv"],
        alias_cyr: ["ўш вилояти", "ошская область", "ўзган", "қорасув"],
      },
      {
        id: 5,
        name: "Jalolobod viloyati",
        indexedName: "jalal-abad",
        center: "Jalolobod",
        alias: ["jalal-abad", "jalolobod", "dzhalal-abad", "toshko'mir"],
        alias_cyr: ["жалолобод", "жалал-абад", "жалолобод вилояти", "тошкўмир"],
      },
      {
        id: 6,
        name: "Issiqko'l viloyati",
        indexedName: "issyk-kul",
        center: "Qoraqo'l",
        alias: ["issyk-kul", "isik-kul", "karakol", "cholpon-ata"],
        alias_cyr: ["иссиқкўл", "иссик-кул", "қорақол", "чолпон-ата"],
      },
      {
        id: 7,
        name: "Norin viloyati",
        indexedName: "naryn",
        center: "Norin",
        alias: ["naryn", "norin", "at-bashi"],
        alias_cyr: ["норин", "нарын", "норин вилояти"],
      },
      {
        id: 8,
        name: "Botken viloyati",
        indexedName: "batken",
        center: "Botken",
        alias: ["batken", "botken", "qizil-qiya", "sulukta"],
        alias_cyr: ["боткен", "баткен", "қизилқия", "сулукта"],
      },
      {
        id: 9,
        name: "Talas viloyati",
        indexedName: "talas",
        center: "Talas",
        alias: ["talas", "talas viloyati", "manas"],
        alias_cyr: ["талас", "талас вилояти", "манас"],
      },
    ],
  },
  {
    indexedName: "tajikistan",
    countryNameCyr: "Тожикистон",
    countryNameLat: "Tojikiston",
    alias: ["tajikistan", "tadjikistan", "tj"],
    alias_cyr: ["тожикистон", "таджикистан", "тж"],
    regions: [
      {
        id: 1,
        name: "Dushanbe",
        indexedName: "dushanbe",
        center: "Dushanbe",
        alias: ["dushanbe", "poytaxt", "dsh"],
        alias_cyr: ["душанбе", "пойтахт", "дшб"],
      },
      {
        id: 2,
        name: "Sug'd viloyati",
        indexedName: "sughd",
        center: "Xujand",
        alias: [
          "sughd",
          "sogd",
          "khujand",
          "xujand",
          "leninobod",
          "khudzhand",
          "konibodom",
          "isfora",
          "panjakent",
        ],
        alias_cyr: [
          "суғд",
          "согд",
          "хужаand",
          "худжанд",
          "ленинобод",
          "конибодом",
          "исфара",
          "панжакент",
        ],
      },
      {
        id: 3,
        name: "Xatlon viloyati",
        indexedName: "khatlon",
        center: "Boxtar",
        alias: [
          "khatlon",
          "boxtar",
          "bokhtar",
          "qurgontepa",
          "kurgan-tyube",
          "kulob",
          "kulyab",
          "norak",
          "nurek",
        ],
        alias_cyr: [
          "хатlon",
          "хатлон",
          "бохтар",
          "қўрғонтепа",
          "курган-тюбе",
          "кулоб",
          "куляб",
          "норак",
          "нурек",
        ],
      },
      {
        id: 4,
        name: "Tog'li-Badaxshon",
        indexedName: "badakhshan",
        center: "Xorug'",
        alias: [
          "badakhshan",
          "badaxon",
          "khorugh",
          "xorug",
          "pamir",
          "pomir",
          "gbao",
        ],
        alias_cyr: ["бадахшон", "хоруғ", "хоруг", "памир", "помир", "гбао"],
      },
    ],
  },
  {
    indexedName: "belarus",
    countryNameCyr: "Беларусь",
    countryNameLat: "Belarusiya",
    alias: ["belarus", "belorussiya", "by"],
    alias_cyr: ["беларусь", "белоруссия", "беларусия", "бй"],
    regions: [
      {
        id: 1,
        name: "Minsk shahri",
        indexedName: "minsk_city",
        center: "Minsk",
        alias: ["minsk city", "poytaxt", "msq"],
        alias_cyr: ["минск шаҳри", "мск"],
      },
      {
        id: 2,
        name: "Minsk viloyati",
        indexedName: "minsk_region",
        center: "Minsk",
        alias: ["minsk", "minskaya", "borisov", "soligorsk"],
        alias_cyr: ["минск", "минская область", "борисов", "солигорск"],
      },
      {
        id: 3,
        name: "Brest viloyati",
        indexedName: "brest",
        center: "Brest",
        alias: ["brest", "brestskaya", "pinsk", "baranovichi"],
        alias_cyr: [
          "брест",
          "брест вилояти",
          "брестская область",
          "пинск",
          "барановичи",
        ],
      },
      {
        id: 4,
        name: "Vitebsk viloyati",
        indexedName: "vitebsk",
        center: "Vitebsk",
        alias: ["vitebsk", "vitsyebsk", "polotsk", "orsha"],
        alias_cyr: [
          "витебск",
          "витебск вилояти",
          "витебская область",
          "полоцк",
          "орша",
        ],
      },
      {
        id: 5,
        name: "Gomel viloyati",
        indexedName: "gomel",
        center: "Gomel",
        alias: ["gomel", "homyel", "mozyr", "zhlobin"],
        alias_cyr: [
          "гомель",
          "гомель вилояти",
          "гомельская область",
          "мозырь",
          "жлобин",
        ],
      },
      {
        id: 6,
        name: "Grodno viloyati",
        indexedName: "grodno",
        center: "Grodno",
        alias: ["grodno", "hrodna", "lida", "slonim"],
        alias_cyr: [
          "гродно",
          "гродно вилояти",
          "гродненская область",
          "лида",
          "слоним",
        ],
      },
      {
        id: 7,
        name: "Mogilev viloyati",
        indexedName: "mogilev",
        center: "Mogilev",
        alias: ["mogilev", "mahibyow", "bobruisk"],
        alias_cyr: ["могилев", "могилёв", "могилев вилояти", "бобруйск"],
      },
    ],
  },
  {
    indexedName: "turkey",
    countryNameCyr: "Туркия",
    countryNameLat: "Turkiya",
    alias: ["turkey", "turkiye", "turkiya", "tr"],
    alias_cyr: ["туркия", "турция", "тр"],
    regions: [
      {
        id: 1,
        name: "Ankara",
        indexedName: "ankara",
        center: "Ankara",
        alias: ["ankara", "capital", "angora"],
        alias_cyr: ["анкара", "пойтахт"],
      },
      {
        id: 2,
        name: "Istanbul",
        indexedName: "istanbul",
        center: "Istanbul",
        alias: ["istanbul", "stambul", "constantinople"],
        alias_cyr: ["истанбул", "стамбул", "истанбул"],
      },
      {
        id: 3,
        name: "Izmir",
        indexedName: "izmir",
        center: "Izmir",
        alias: ["izmir", "smirna"],
        alias_cyr: ["измир", "измир"],
      },
      {
        id: 4,
        name: "Antalya",
        indexedName: "antalya",
        center: "Antalya",
        alias: ["antalya", "antaliya", "alanya"],
        alias_cyr: ["анталья", "анталия", "аланья"],
      },
      {
        id: 5,
        name: "Bursa",
        indexedName: "bursa",
        center: "Bursa",
        alias: ["bursa", "brusa"],
        alias_cyr: ["бурса", "бурса"],
      },
      {
        id: 6,
        name: "Adana",
        indexedName: "adana",
        center: "Adana",
        alias: ["adana"],
        alias_cyr: ["адана", "адана"],
      },
      {
        id: 7,
        name: "Gaziantep",
        indexedName: "gaziantep",
        center: "Gaziantep",
        alias: ["gaziantep", "antep"],
        alias_cyr: ["газиантеп", "антеп"],
      },
      {
        id: 8,
        name: "Konya",
        indexedName: "konya",
        center: "Konya",
        alias: ["konya", "iconium"],
        alias_cyr: ["конья", "қўня"],
      },
    ],
  },
];
